### ISSUE TITLE
Verify if less environmental variables can be used for OpenStack RC file

### ISSUE THREAD

**Issue by carmat88** [kubenow/KubeNow#102]
Based on the [OpenStack documentation](https://docs.openstack.org/user-guide/common/cli-set-environment-variables-using-openstack-rc.html#download-and-source-the-openstack-rc-file), it seems that some environmental variables can be omitted whereas in the [KubeNow latest guidelines](http://kubenow.readthedocs.io/en/latest/getting_started/bootstrap.html) it is being recommended otherwise.

Thus investigate if all those variables are needed based on the usage of Embassy Cloud platform.

**HINT:** Try a different OpenStack platform

**Comment by mcapuccini** [comment]
@carmat88 I verified this. The problem is with v2/v3 of the OpenStack keystone endpoint. We can remove the whole section about the variables, and add in troubleshooting that when you get `You must provide exactly one of DomainID or DomainName to authenticate by Username` either from terraform or packer, then you need to set `OS_DOMAIN_NAME` in your environment.

**Comment by carmat88** [comment]
@mcapuccini Great, thanks for this follow-up. Will draft these changes and send a PR.

**Comment by carmat88** [comment]
@mcapuccini Doc revised and PR created: https://github.com/kubenow/docs/pull/5 . I remain at disposal for any further modification.
