### ISSUE TITLE
Make sure there is only one Azure image with same name

### ISSUE THREAD

**Issue by andersla** [kubenow/KubeNow#283]
Azure packer allows for duplicate image names with unique id:s. We should make sure it is not possible in travis build. One option would be to do a az image show "$name" and see it image before travis executes packer builder. Lets discuss alternatives.

**Comment by mcapuccini** [comment]
What if we delete the image if present at the beginning of the build?

**Comment by andersla** [comment]
Thats an option, but a little bit more difficult to implement, It should be extremely rare that an image with same name is created or?

**Comment by andersla** [comment]
Or maybe not more difficult - I dont really now:-)

**Comment by carmat88** [comment]
Hey guys. As per our discussion, on the packer's github I found a [month old issue](https://github.com/hashicorp/packer/issues/5509) that may be related. Before following up in that thread, I would like to perform and investigate these scenarios:

1. Create a v040b2 tag, delete it and then re-create again in order to evaluate whether and where duplicates are being created in our providers

2. Creating a new branch to investigate this packer glitch (which will create images’ name with -test as suffixes), push commits and then launch rebuild from Travis and check whether --force is overwriting whatsoever

**Comment by mcapuccini** [comment]
Fixed: https://github.com/kubenow/image/pull/29
